version: "3.8"
services:
  app:
    image: python:3.11
    container_name: scraping-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "pip install -r requirements.txt && python main.py"
    restart: always
