version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    image: python:3.11
    container_name: scraping-app
    volumes:
      - ./:/app
    restart: always
