version: "3.8"
services:
  app:
    image: python:3.11
    container_name: scraping-app
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "pip install -r /app/requirements.txt && python /app/main.py"
    restart: always
